### ISSUE TITLE
Not working when called from a C++ namespace

### ISSUE THREAD

**Issue by Dids** [cyrilcode/embed-resource#4]
I've been ripping my hair out trying to figure this one out, but for some reason this doesn't work when the resources are loaded from within a namespace in C++ (`LOAD_RESOURCE` calls), resulting in undefined symbols.

From what I can tell, it's trying to load the resources with the current namespace appended (`MyNamespace::_resource_MyResources`), which naturally fails.  
I went a step further and tried to convert the logic/code from C to C++, so each resource would actually already exist in the same namespace, but that resulted in the same undefined symbols.

Just to reiterate: if I use the same exact code in the global/anonymous namespace (eg. without a namespace), everything _just works_, but when called from within any kind of namespace, it all breaks down and I have no idea.

I'm really, really hoping someone could shed some light on this and hopefully provide a solution/workaround. I'll see about opening a StackOverflow question regarding this as well, as this might just be a quirk with CMake etc.

**Comment by Dids** [comment]
https://stackoverflow.com/questions/49775353/issues-embedding-resources-from-a-namespace-c-cmake

**Comment by darrenmothersele** [comment]
You'll need to add the namespace to the code generated by `embedresource.cpp`.

https://github.com/cyrilcode/embed-resource/blob/master/embedresource.cpp#L31

Ideally you'd want to add that as a parameter, when `embedresource.cpp` is called.

Hope that's helpful.

**Comment by Dids** [comment]
You were absolutely right.

I converted the entire thing to C++, and through a few hurdles got it working, including namespaces as parameters.

There are still a few occasions where it's omitting the namespace from the resource, which breaks it again, but at least it's partially working.
