### ISSUE TITLE
Load .glsl with extra character at the end of the string?

### ISSUE THREAD

**Issue by penguin1214** [cyrilcode/embed-resource#5]
Hi. Thanks for creating this great tool!

I'm facing some trouble when using it. I loaded two `.glsl` files but there are always a duplicated `}` at the end of the loaded data. I tested to delete the one `}` in my shader file, but the problem persists. I then changed the `}` in my file to some other characters, there were always a copy of that character.

The output:

```
#version 330 core

out vec4 fragColor;

void main() {
    fragColor = vec4(0.5, 0.1, 0.8, 1.0);
}}
```

My loading code:

```
include_directories(ext/embed-resource)
add_subdirectory(ext/embed-resource)

embed_resources(MyResources resources/shaders/test_vs.glsl resources/shaders/test_fs.glsl)

 add_executable(target src/MyUtils.cpp src/proj1.cpp ${MyResources})

////////////////////////////////////////
        Resource test_vs = LOAD_RESOURCE(test_vs_glsl);
        Resource test_fs = LOAD_RESOURCE(test_fs_glsl);
```

I don't see any related issue on this, so may be I'm loading the resource incorrectly? Could you check if this is a bug? Thanks!

**Comment by schneeregenflocke** [comment]
Hi. I also like the idea of the tool. Also had problems using the tool and therefore created a topic in the [german-speaking C++-forum](https://www.c-plusplus.net/forum/topic/350374/embed-resource) So I changed the macro LOAD_RESOURCE. Also to temporarily solve the problem with the extra character at the end of the string.

```
#include "Resource.h"

#ifdef LOAD_RESOURCE
#undef LOAD_RESOURCE
#endif

#define LOAD_RESOURCE(RESOURCE, VARIABLE) \
        extern "C" const char _resource_##RESOURCE[]; extern "C" const size_t _resource_##RESOURCE##_len; \
        Resource VARIABLE = Resource(_resource_##RESOURCE, _resource_##RESOURCE##_len - 1);
```

**Comment by maximiliank** [comment]
It was an error in the embedding function, see Pull request https://github.com/cyrilcode/embed-resource/pull/7.

**Comment by darrenmothersele** [comment]
PR merged
