### ISSUE TITLE
Tool did not work immediately

### ISSUE THREAD

**Issue by schneeregenflocke** [cyrilcode/embed-resource#6]
Thanks for the tool.

The tool did not work immediately, so I opened a thread in the german language [C++ Community](https://www.c-plusplus.net/forum/topic/350374/embed-resource).

Among other things I noticed the same as described in [Load .glsl with extra character at the end of the string?](https://github.com/cyrilcode/embed-resource/issues/5#issue-405059139)

kind regards

**Comment by darrenmothersele** [comment]
Should be solved by the PRs now merged
