### ISSUE TITLE
Migrate to cpp17

### ISSUE THREAD

**Issue by WilliamTambellini** [cyrilcode/embed-resource#8]
Hi
Would using cpp17 std filesystem remove the dep with boost ?

**Comment by darrenmothersele** [comment]
Yes, there's a PR here: https://github.com/cyrilcode/embed-resource/pull/2
Getting some 👁️ on that would be helpful :)

**Comment by darrenmothersele** [comment]
PR merged

**Comment by WilliamTambellini** [comment]
Cool @darrenmothersele 
Should the readme be updated ? still:
"Embed binary files and resources (such as GLSL Shader source files) into C++ projects. Uses C++11 features and Boost for filesystem."
